version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: mtu_elec
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana

  main_app:
    image: ubuntu:latest
    container_name: main_app_container
    volumes:
      - .:/  # Montez le répertoire courant de l'hôte dans /app du conteneur
    depends_on:
      - postgres
      - grafana
    entrypoint: >
      bash -c "
      # Mettre à jour les paquets et installer les dépendances
      apt-get update && apt-get install -y python3 python3-pip python3-venv;
      # Créer et activer l'environnement virtuel
      python3 -m venv ml;
      source ml/bin/activate;
      # Installer les dépendances
      pip install -r /app/requirements.txt;
      # Exécuter le script Python
      python /app/Main.py;
      # Garder le conteneur en cours d'exécution
      tail -f /dev/null
      "
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
  grafana_data:
