version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: mtu_elec
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana

  main_app:
    image: python:3.8-slim
    container_name: main_app_container
    volumes:
      - .:/app  # Montez le répertoire courant de l'hôte dans /app du conteneur
    depends_on:
      - postgres
      - grafana
    working_dir: /app  # Définit le répertoire de travail
    command: >
      bash -c "
      pip install --no-cache-dir -r requirements.txt;
      python Main.py;
      tail -f /dev/null
      "
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  postgres_data:
  grafana_data:
