version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_DB: mtu_elec
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana

  main_app:
    image: python:3.9
    container_name: main_app_container
    depends_on:
      - postgres
      - grafana
    entrypoint: >
      bash -c "
      # Activate the environment and run the Python script
      source myenv/bin/activate;
      "
    environment:
      - PYTHONUNBUFFERED=1
volumes:
  postgres_data:
  grafana_data:
