name: Deploy AI_MTU Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Clean repository
        run: |
          sudo rm -rf /home/ubuntu/actions-runner/_work/AI_MTU/AI_MTU/*
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and start Docker containers
        run: |
          docker-compose down  # Nettoie les anciens conteneurs si nécessaire
          docker-compose up -d  # Démarre les conteneurs en arrière-plan

      - name: Wait for PostgreSQL to be ready
        run: |
          until docker-compose exec -T postgres pg_isready -h postgres -p 5432; do
            echo "Waiting for PostgreSQL...";
            sleep 5;
          done

      - name: Wait for Grafana to be ready
        run: |
          until curl -s http://localhost:3000/api/health | grep '"database": "ok"'; do
            echo "Waiting for Grafana...";
            sleep 5;
          done
          
      - name: Run Main.py
        run: |
          docker-compose exec -T main_app python3 /app/Main.py



