name: Deploy AI_MTU Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and start Docker containers
        run: |
          cd AI_MTU
          docker-compose up -d
