name: Deploy Pipeline

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker-compose build

      - name: Run Docker containers
        run: docker-compose up -d

      - name: Execute Main.py in the container
        run: docker-compose exec <nom_du_service> python Main.py

      - name: Stop and remove Docker containers
        if: always()
        run: docker-compose down
